### ISSUE TITLE
nancheng1994

### ISSUE THREAD

**Issue by nancheng1994** [ftyszyx/feishu-vitepress#2]
大佬您好，根据您的步骤部署的网站，评论区用artalk还需要额外部署服务器，不然就显示（我看您的网页也显示这个）
Artalk Error
Failed to load comments
TypeError: Failed to fetch

Retry

，可否更换为[Giscus](https://giscus.app/zh-CN)？

**Comment by ftyszyx** [comment]
好的，我也觉得arttalk不好用，我先看下，谢谢建议

**Comment by ftyszyx** [comment]
已经使用giscus配好了，[ 说明](https://github.com/ftyszyx/feishu-vitepress?tab=readme-ov-file#%E5%88%A0%E9%99%A4artalk%E4%BD%BF%E7%94%A8giscus%E5%81%9A%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F)
相当完美，感谢推荐这么好的东西

**Comment by nancheng1994** [comment]
大佬效率真高
